export const projects = [
  {
    slug: "fraud-ml-pipeline",
    title: "End-to-end ML pipeline for fraud detection",
    summary: "Feature store + sklearn + MLflow + FastAPI serving",
    tech: ["Python", "scikit-learn", "MLflow", "FastAPI", "Docker"],
    repo: "https://github.com/yourusername/fraud-ml-pipeline",
    demo: "https://your-fraud-demo.vercel.app",
    metrics: "AUC 0.94, latency 85ms",
    image: "/projects/fraud.png",
  },
  {
    slug: "nlp-transformer",
    title: "Transformer-based NLP text classifier",
    summary: "Fine-tuned DistilBERT with W&B experiments and Gradio demo",
    tech: ["Python", "PyTorch", "Transformers", "W&B", "Gradio"],
    repo: "https://github.com/yourusername/nlp-transformer-classifier",
    demo: "https://huggingface.co/spaces/yourusername/text-classifier",
    metrics: "F1 0.86 vs baseline 0.78",
    image: "/projects/nlp.png",
  },
  {
    slug: "cv-inference-service",
    title: "Computer vision inference microservice",
    summary: "YOLOv5 object detection served via FastAPI + Docker",
    tech: ["Python", "PyTorch", "YOLOv5", "FastAPI", "Docker"],
    repo: "https://github.com/yourusername/cv-inference-service",
    demo: "https://your-cv-demo.vercel.app",
    metrics: "mAP@50 0.72, p95 latency 120ms",
    image: "/projects/cv.png",
  },
];